# GitLab Dashboard Full-Stack - Docker Setup
version: '3.8'

services:
  # Flask API Backend
  flask-api-backend:
    build: 
      context: ./flask-api-backend
      dockerfile: Dockerfile
    container_name: gitlab-dashboard-api
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - GITLAB_URL=${GITLAB_URL:-https://gitlab.com}
      - GITLAB_TOKEN=${GITLAB_TOKEN}
      - SECRET_KEY=${SECRET_KEY:-your-secret-key}
    volumes:
      - ./flask-api-backend/.env:/app/.env:ro
    networks:
      - gitlab-dashboard-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # React Frontend
  react-dashboard-frontend:
    build:
      context: ./react-dashboard-frontend
      dockerfile: Dockerfile
    container_name: gitlab-dashboard-frontend
    ports:
      - "80:80"
    depends_on:
      flask-api-backend:
        condition: service_healthy
    networks:
      - gitlab-dashboard-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  gitlab-dashboard-network:
    driver: bridge

volumes:
  gitlab-data:
    driver: local
